# Generated by Django 3.2 on 2023-06-02 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xSize', models.CharField(default='0', max_length=5)),
                ('ySize', models.CharField(default='0', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('isPreview', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=-1)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.house')),
            ],
        ),
    ]
