# Generated by Django 3.2 on 2023-06-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
