# Generated by Django 3.2 on 2023-06-09 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20230609_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='buildArea',
            new_name='area',
        ),
    ]
