# Generated by Django 3.2 on 2023-06-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_buildarea_house_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='price',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
